// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import RadioSelectionController from "./radio_selection_controller"
application.register("radio-selection", RadioSelectionController)

import ResetFormController from "./reset_form_controller"
application.register("reset-form", ResetFormController)
